#language: java
#jdk: openjdk8
#script:
#  - jdk_switcher use openjdk10
#  - # do stuff with OpenJDK 10
#  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
#  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
#  - export JAVA_HOME=$HOME/openjdk11
#  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
#  - ./mvnw clean install
#
#cache:
#  directories:
#    - $HOME/.m2
#mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#mvn test -B
#mvn surefire-report:report
#arch: amd64
language: java

jdk: openjdk8
cache:
  directories:
    - $HOME/.m2
sudo: false
script:
  - java --version
  - mvn clean install
  - mvn cobertura:cobertura
  - mvn clean package
  - mvn test


name: Codecov
uses: codecov/codecov-action@v3.0.0

after_success:
  - bash <(curl -s https://codecov.io/bash)